### ISSUE TITLE
2 or more fields @ thingspeak

### ISSUE THREAD

**Issue by ericmatgithub** [dragino/Arduino-Profile-Examples#10]
hi all

code works fine on my LG01.
field1 is smoothly updated on api.thingspeak

i am struggling adding 2 or more fields:

just uncommenting these two lines:
                    //dataString ="field2=";
                    //dataString += h;
doensnt make sense.
Then I loose field1; as datastring is refilled with field2 in stead of field1

furthermore 2nd line must be hh in stead of h. That's clear :-) 

anyone suggestions how to update the code in an easy / logical way?

thanks
eric
ps. this is regarding this peace of code: 
https://github.com/dragino/Arduino-Profile-Examples/tree/master/libraries/Dragino/examples/IoTServer/ThingSpeak/LG01_ThingSpeak_RESTful_Single_Data

**Comment by dragino** [comment]
Bug fix, new code: 
                 dataString ="field1=";
                    dataString += th;
                    dataString +=".";
                    dataString += tl;
                    dataString +="&field2=";
                    dataString += hh;
                    dataString +=".";
                    dataString += hl;

More efficient can use MQTT code, check manual.

**Comment by ericmatgithub** [comment]
great, this should work :-)
